apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# kyverno installation manifests
- https://github.com/kyverno/kyverno/releases/download/v1.10.0/install.yaml
# PullSecretPolicy 
#- pullsecret-policy.yaml

namespace: kyverno