#ATTU Frontend
attu:
  enabled: true
  name: attu
  ingress:
    enabled: true
    annotations: {
      cert-manager.io/cluster-issuer: letsencrypt-prod
    }
    ingressClassName: nginx
    hosts:
      - attu-dev.supportgpt.dachlab.net
    tls:
    - hosts:
        - attu-dev.supportgpt.dachlab.net
      secretName: attu-dev-tld-secret

# imagePullSecrets, most images are hosted on docker.io
# image:
#   all:
#     pullSecrets:
#     - regcred
# etcd:
#   image:
#     pullSecrets:
#     - regcred

# Milvus Cluster Mode
dataCoordinator:
  replicas: 2
  activeStandby: 
    enabled: True
dataNode:
  replicas: 2
indexCoordinator:
  replicas: 2
indexNode:
  replicas: 2
queryCoordinator:
  replicas: 2
  activeStandby: 
    enabled: True
queryNode:
  replicas: 2
rootCoordinator:
  replicas: 2
  activeStandby: 
    enabled: True

# Exposing Milvus externally, only for migration phase
service:
  type: LoadBalancer

# Enabling Service Monitor
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      monitoring: apps
# Disable MinIO and configuring External S3
minio:
  enabled: false
externalS3:
  enabled: true
  host: "host"
  port: "80"
  accessKey: "abc"
  secretKey: "abc"
  useSSL: false
  bucketName: "milvus"
  rootPath: ""
  region: "us-east-1"
  useVirtualHost: false