dataCoordinator:
  replicas: 2
  activeStandby: 
    enabled: True
dataNode:
  replicas: 2
indexCoordinator:
  replicas: 2
indexNode:
  replicas: 2
queryCoordinator:
  replicas: 2
  activeStandby: 
    enabled: True
queryNode:
  replicas: 2
rootCoordinator:
  replicas: 2
  activeStandby: 
    enabled: True
dataNode:
  replicas: 2
service:
  type: LoadBalancer
minio:
  enabled: false
attu:
  enabled: true
  name: attu
  service:
    type: LoadBalancer

###################################
# External S3
# - these configs are only used when `externalS3.enabled` is true
###################################
externalS3:
  enabled: true
  host: "objects.blaze.dachlab.net"
  port: "80"
  accessKey: "706ehpqy_BHab3rcA50KcqtnhK5vNiLg"
  secretKey: "vpYgEzyCDDocNoBliNSALMFyiSEJSIWn"
  useSSL: false
  bucketName: "milvus"
  rootPath: ""
  region: "us-east-1"
  useVirtualHost: false