apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# cert-manager installation manifests
- https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml

namespace: cert-manager