apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-volume
  namespace: jupyterhub
spec:
  storageClassName: nutanix-files
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi