singleuser:
  defaultUrl: "/lab"
  storage:
    capacity: 100Gi
### Remove Extra Volumes if no shared (NFS-based) folder is used
    # extraVolumes:
    #   - name: jupyterhub-shared
    #     persistentVolumeClaim:
    #       claimName: jupyterhub-shared-volume
    # extraVolumeMounts:
    #   - name: jupyterhub-shared
    #     mountPath: /home/jovyan/shared
  extraTolerations: [{"key": "dedicated", "operator": "Equal", "value": "gpu", "effect": "NoSchedule"}]
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "GPU Server"
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
  networkPolicy:
    egressAllowRules:
      cloudMetadataServer: true
      privateIPs: true
  cloudMetadata:
    blockWithIptables: false
hub:
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - user1
        - user2
        - user3
        - user4
    DummyAuthenticator:
      password: nutanix.1
    JupyterHub:
      authenticator_class: dummy
proxy:
  service:
    type: ClusterIP
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - jupyter.gptdev1.cloudnative.nvdlab.net
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 900m
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - hosts:
        - jupyter.gptdev1.cloudnative.nvdlab.net
      secretName: jupyter-tld-secret