imagePullSecrets:
  - name: regcred
mode: deployment
replicaCount: 1
presets:
  clusterMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
  processors:
    batch:
      send_batch_size: 10000
      timeout: 10s
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
  exporters:
    otlp/uptrace:
      endpoint: uptrace-grpc.gptmgmt.cloudnative.nvdlab.net:443
      tls:
        insecure: false
      headers:
        uptrace-dsn: 'http://project2_secret_token@localhost:14317/2'
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/uptrace]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/uptrace]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/uptrace]