mode: daemonset
presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true
  kubernetesAttributes:
    enabled: true
    # You can also configure the preset to add all of the associated pod's labels and annotations to you telemetry.
    # The label/annotation name will become the resource attribute's key.
    extractAllPodLabels: true
    extractAllPodAnnotations: true
  kubeletMetrics:
    enabled: true
  hostMetrics:
    enabled: true

extraEnvs:
  - name: NODE_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP

config:
  receivers:
    kubeletstats:
      endpoint: 'https://${env:NODE_IP}:10250'
      insecure_skip_verify: true
  processors:
    batch:
      send_batch_size: 10000
      timeout: 10s
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
  exporters:
    otlp/central:
      endpoint: opentelemetry-collector-deployment:4317
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        exporters:
          - otlp/central
      metrics:
        exporters:
          - otlp/central
      traces:
        exporters:
          - otlp/central