apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress-nginx-ns.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx
    version: 4.8.3
    valuesFile: values.yaml