listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
externalAccess:
  enabled: true
  controller:
    service:
      type: ClusterIP
      ports:
        external: 9094
      domain: 'kafka.gpt01mgmt01.cloudnative.nvdlab.net'
  broker:
    service:
      type: ClusterIP
      port:
        external: 9094
      domain: 'kafka.gpt01mgmt01.cloudnative.nvdlab.net'
#  service:
#    broker:
#      type: NodePort
#      ports:
#        external: 9094
#    controller:
#      type: NodePort
#      containerPorts:
#        external: 9094
#  autoDiscovery:
#    enabled: true
serviceAccount:
  create: true
rbac:
  create: true
