apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-bootstrap
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - matrix:
          generators:
          # enriches applications per directory in clusters/base with cluster labels
          - clusters: {}
          # produces argocd app per directory in clusters/base
          - git:
              repoURL: &repo https://github.com/wolfganghuse/nai-infra.git
              directories:
              - path: clusters/base/*
    generators:
      - git:
          repoURL: https://github.com/wolfganghuse/nai-infra.git
          revision: working-branch
          files:
          - path: argo-apps/cluster-config.yaml
      - list:
          elements: []
          elementsYaml: "{{ .key.clusters | toJson }}"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: system
      source:
        repoURL: *repo
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true